name: invokeai
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.9, <3.10
  - pip>=22.2

  # pytorch left unpinned
  - pytorch
  - torchvision
  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/invokeai/invokeai-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n invokeai-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```
  - albumentations
  - coloredlogs
  - einops
  - grpcio
  - humanfriendly
  - imageio
  - imageio-ffmpeg
  - imgaug
  - kornia
  - mpmath
  - nomkl
  - numpy
  - omegaconf
  - openh264
  - onnx
  - onnxruntime
  - pudb
  - pytorch-lightning
  - scipy
  - streamlit
  - sympy
  - tensorboard
  - torchmetrics
  - pip:
      - flask==2.1.3
      - flask_socketio==5.3.0
      - flask_cors==3.0.10
      - dependency_injector==4.40.0
      - eventlet==0.33.1
      - protobuf==3.19.6
      - realesrgan==0.2.5.0
      - send2trash==1.8.0
      - test-tube==0.7.5
      - transformers==4.21.3
      - torch-fidelity==0.3.0
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
      - -e git+https://github.com/TencentARC/GFPGAN.git#egg=gfpgan
      - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
