name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.9
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - opencv-python==4.5.5.64
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - realesrgan==0.2.5.0
    - test-tube>=0.7.5
    - streamlit==1.12.0
    - send2trash==1.8.0
    - pillow==9.2.0
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.6.0
    - flask==2.1.3
    - flask_socketio==5.3.0
    - flask_cors==3.0.10
    - dependency_injector==4.40.0
    - eventlet
    - kornia==0.6.0
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
    - -e git+https://github.com/lstein/GFPGAN@fix-dark-cast-images#egg=gfpgan
    - -e .
