name: ldm
channels:
  - pytorch
  - conda-forge
dependencies:
  - python==3.10.5
  - pip==22.2.2
 
  # pytorch left unpinned
  - pytorch
  - torchvision

  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/ldm/ldm-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n ldm-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```
  - albumentations==1.2.1
  - coloredlogs==15.0.1
  - einops==0.4.1
  - grpcio==1.46.4
  - humanfriendly==10.0
  - imageio==2.21.2
  - imageio-ffmpeg==0.4.7
  - imgaug==0.4.0
  - kornia==0.6.7
  - mpmath==1.2.1
  - nomkl
  - numpy==1.23.2
  - omegaconf==2.1.1
  - openh264==2.3.0
  - onnx==1.12.0
  - onnxruntime==1.12.1
  - protobuf==3.19.4
  - pudb==2022.1
  - pytorch-lightning==1.7.5
  - scipy==1.9.1
  - streamlit==1.12.2
  - sympy==1.10.1
  - tensorboard==2.10.0
  - torchmetrics==0.9.3
  - pip:
    - flask==2.1.3
    - flask_socketio==5.3.0
    - flask_cors==3.0.10
    - dependency_injector==4.40.0
    - eventlet
    - opencv-python==4.6.0
    - protobuf==3.20.1
    - realesrgan==0.2.5.0
    - send2trash==1.8.0
    - test-tube==0.7.5
    - transformers==4.21.2
    - torch-fidelity==0.3.0
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
    - -e git+https://github.com/lstein/GFPGAN@fix-dark-cast-images#egg=gfpgan
    - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
